version: '1.0'

services:
    mosquitto:
        image: eclipse-mosquitto
        container_name: mqtt-server
        ports:
            - 1883:1883 #default mqtt port
            - 9001:9001 #default mqtt port for websocket
        volumes:
            # local:container:access
            - C:\mosquitto\config\mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
            - C:\mosquitto\config\mosquitto.passwd:/mosquitto/config/mosquitto.passwd
            - C:\mosquitto\log\mosquitto.log:/mosquitto/log/mosquitto.log:rw
            - C:\mosquitto\data:/mosquitto/data:rw
        networks:
            - mosquitto
networks:
    mosquitto:
        name: mosquitto
        driver: bridge